name: Updater2Discord

on:
  push:
    branches:
      - main
    paths:
      - 'src/Runtime.luau'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Runtime
        env:
          WebhookURL: ${{ secrets.webhook }}
          Message: ${{ github.event.head_commit.message }}
          Author: ${{ github.event.head_commit.author.name }}
          CommitURL: ${{ github.event.head_commit.url }}
          Repository: ${{ github.repository }}
        run: node scripts/Updater.js
